### ISSUE TITLE
Can't get "$" Symbol to work

### ISSUE THREAD

**Issue by KceGio** [dougbenham/TerrariaPatcher#2]
What version of C# is supported?

**Comment by trigger-death** [comment]
Goto Project Settings > Build Tab > Advanced Button (near the bottom right) > Language Version:

This will tell you what version is being used.

![image](https://user-images.githubusercontent.com/9752430/50539061-de335380-0b47-11e9-8f5e-d02f28d2d4b2.png)

**Comment by dougbenham** [comment]
$ symbol is for string interpolation which is in C# 6.
